# =============================================================================
#  embed_files.cmake  (run with cmake -P at BUILD time)
#
#  Turns every file of a plugin folder into a C++ source defining a
#  jsfx::EmbeddedBundle named jsfx_generated::kBundle.
#
#  -DSRC_DIR=<plugin folder>  -DOUT=<file.cpp>  -DMAIN=<relative .jsfx path>
#  -DSYMBOL=<name>  (default kBundle, in namespace jsfx_generated)
#  -DEXCLUDE="plugin.json;..." (relative paths or globs, ';' separated)
# =============================================================================
cmake_minimum_required(VERSION 3.20)

if(NOT DEFINED SYMBOL)
  set(SYMBOL kBundle)
endif()

foreach(_v SRC_DIR OUT MAIN)
  if(NOT DEFINED ${_v})
    message(FATAL_ERROR "embed_files.cmake: -D${_v}=... is required")
  endif()
endforeach()

file(GLOB_RECURSE _files RELATIVE "${SRC_DIR}" LIST_DIRECTORIES false "${SRC_DIR}/*")
list(SORT _files)

set(_kept "")
foreach(_f ${_files})
  set(_skip FALSE)
  # editor / OS clutter
  if(_f MATCHES "(^|/)\\.(DS_Store|git|svn)|~$|\\.swp$|(^|/)Thumbs\\.db$")
    set(_skip TRUE)
  endif()
  foreach(_ex ${EXCLUDE})
    if(_f STREQUAL _ex OR _f MATCHES "^${_ex}$")
      set(_skip TRUE)
    endif()
  endforeach()
  if(NOT _skip)
    list(APPEND _kept "${_f}")
  endif()
endforeach()

if(NOT "${MAIN}" IN_LIST _kept)
  message(FATAL_ERROR "embed_files.cmake: main file '${MAIN}' not found in ${SRC_DIR}")
endif()

set(_body "")
set(_table "")
set(_hash_input "")
set(_i 0)
foreach(_f ${_kept})
  file(READ "${SRC_DIR}/${_f}" _hex HEX)
  file(SHA256 "${SRC_DIR}/${_f}" _fsha)
  string(APPEND _hash_input "${_f}:${_fsha};")
  string(LENGTH "${_hex}" _len)
  math(EXPR _size "${_len} / 2")
  if(_size EQUAL 0)
    string(APPEND _body "const unsigned char f${_i}[1] = {0};\n")
  else()
    # 0x.. bytes, 32 per line
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytes "${_hex}")
    string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){32})" "\\1\n" _bytes "${_bytes}")
    string(APPEND _body "const unsigned char f${_i}[${_size}] = {\n${_bytes}\n};\n")
  endif()
  string(REPLACE "\\" "\\\\" _cpath "${_f}")
  string(REPLACE "\"" "\\\"" _cpath "${_cpath}")
  string(APPEND _table "  {\"${_cpath}\", f${_i}, ${_size}},\n")
  math(EXPR _i "${_i} + 1")
endforeach()

string(SHA256 _hash "${_hash_input}")
string(SUBSTRING "${_hash}" 0 16 _hash)

set(_content "// Generated by cmake/scripts/embed_files.cmake - do not edit.
#include \"JsfxEmbedded.h\"

namespace {
${_body}
const jsfx::EmbeddedFile kFiles[] = {
${_table}};
} // namespace

namespace jsfx_generated {
extern const jsfx::EmbeddedBundle ${SYMBOL};
const jsfx::EmbeddedBundle ${SYMBOL} = {kFiles, ${_i}, \"${MAIN}\", \"${_hash}\"};
} // namespace jsfx_generated
")

if(EXISTS "${OUT}")
  file(READ "${OUT}" _old)
  if(_old STREQUAL _content)
    return()
  endif()
endif()
file(WRITE "${OUT}" "${_content}")
