// =============================================================================
//  jsfx_meta  -  build-time generator
//
//  Reads the plugin's JSFX header with ysfx itself (exactly the parser used at
//  run time) and emits:
//    jsfx_meta.h       macros used by config.h (I/O, @gfx size, UI size...)
//    jsfx_params.inc   the host parameter table (one entry per slider)
//
//  usage: jsfx_meta <main.jsfx> <import_root> <data_root> <out_dir>
//  Fails the build (exit 1) when the JSFX header can't be parsed.
// =============================================================================
#include <algorithm>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include "ysfx.h"

namespace {

std::string CString(const std::string& s)
{
  // ASCII as is, everything else as octal escapes (MSVC without /utf-8 would
  // otherwise re-encode UTF-8 names such as "Fréquence").
  std::string out = "\"";
  for (unsigned char c : s)
  {
    if (c == '\\' || c == '"') { out += '\\'; out += static_cast<char>(c); }
    else if (c >= 0x20 && c < 0x7f && c != '?') out += static_cast<char>(c);
    else
    {
      char buf[8];
      std::snprintf(buf, sizeof buf, "\\%03o", c);
      out += buf;
    }
  }
  return out + "\"";
}

std::string Num(double v)
{
  char buf[64];
  std::snprintf(buf, sizeof buf, "%.17g", v);
  std::string s = buf;
  if (s.find_first_of(".eEn") == std::string::npos) s += ".0";
  return s;
}

bool WriteIfChanged(const std::string& path, const std::string& content)
{
  {
    std::ifstream in(path, std::ios::binary);
    if (in)
    {
      std::stringstream ss;
      ss << in.rdbuf();
      if (ss.str() == content) return true;
    }
  }
  std::ofstream out(path, std::ios::binary | std::ios::trunc);
  out << content;
  return static_cast<bool>(out);
}

void Log(intptr_t, ysfx_log_level level, const char* msg)
{
  std::fprintf(stderr, "jsfx_meta: %s: %s\n", ysfx_log_level_string(level), msg);
}

// Generic fallback UI: knobs on a grid (must match JsfxPlugin.cpp)
constexpr int kKnobsPerRow = 6, kCellW = 110, kCellH = 120, kHeaderH = 60, kMargin = 20;

} // namespace

int main(int argc, char** argv)
{
  if (argc != 5)
  {
    std::fprintf(stderr, "usage: jsfx_meta <main.jsfx> <import_root> <data_root> <out_dir>\n");
    return 2;
  }
  const std::string jsfxPath = argv[1], outDir = argv[4];

  ysfx_config_t* config = ysfx_config_new();
  ysfx_set_import_root(config, argv[2]);
  ysfx_set_data_root(config, argv[3]);
  ysfx_set_log_reporter(config, &Log);
  ysfx_t* fx = ysfx_new(config);
  ysfx_config_free(config);

  if (!ysfx_load_file(fx, jsfxPath.c_str(), 0))
  {
    std::fprintf(stderr, "jsfx_meta: cannot parse %s\n", jsfxPath.c_str());
    ysfx_free(fx);
    return 1;
  }
  // Compile too: syntax errors then fail the build instead of the plugin.
  if (!ysfx_compile(fx, 0))
  {
    std::fprintf(stderr, "jsfx_meta: %s does not compile (see errors above)\n", jsfxPath.c_str());
    ysfx_free(fx);
    return 1;
  }

  const uint32_t nIn = ysfx_get_num_inputs(fx);
  const uint32_t nOut = ysfx_get_num_outputs(fx);
  const bool hasGfx = ysfx_has_section(fx, ysfx_section_gfx);
  uint32_t dim[2] = {0, 0};
  ysfx_get_gfx_dim(fx, dim);

  std::ostringstream params;
  params << "// Generated by jsfx_meta from " << jsfxPath << " - do not edit.\n"
         << "#pragma once\n#include \"JsfxEngine.h\"\n\n";

  std::vector<std::string> entries;
  int numVisible = 0;
  for (uint32_t i = 0; i < ysfx_max_sliders; ++i)
  {
    if (!ysfx_slider_exists(fx, i)) continue;
    ysfx_slider_curve_t c{};
    ysfx_slider_get_curve(fx, i, &c);
    const bool isEnum = ysfx_slider_is_enum(fx, i);
    const bool visible = ysfx_slider_is_initially_visible(fx, i);
    numVisible += visible ? 1 : 0;

    std::string enumRef = "nullptr";
    uint32_t nEnum = 0;
    if (isEnum)
    {
      nEnum = ysfx_slider_get_enum_size(fx, i);
      if (nEnum)
      {
        params << "static const char* const kJsfxEnum" << i << "[] = {";
        for (uint32_t e = 0; e < nEnum; ++e)
          params << (e ? ", " : "") << CString(ysfx_slider_get_enum_name(fx, i, e));
        params << "};\n";
        enumRef = "kJsfxEnum" + std::to_string(i);
      }
    }
    std::string name = ysfx_slider_get_name(fx, i);
    if (name.empty()) name = "slider" + std::to_string(i + 1);

    std::ostringstream e;
    e << "  {" << i << ", " << CString(name) << ", " << Num(c.def) << ", " << Num(c.min) << ", "
      << Num(c.max) << ", " << Num(c.inc) << ", " << int(c.shape) << ", " << Num(c.modifier) << ", "
      << (isEnum ? "true" : "false") << ", " << (visible ? "true" : "false") << ", "
      << enumRef << ", " << nEnum << "},";
    entries.push_back(e.str());
  }

  params << "\nstatic const jsfx::ParamDef kJsfxParams[] = {\n";
  for (auto& e : entries) params << e << "\n";
  if (entries.empty()) params << "  {0, \"\", 0.0, 0.0, 1.0, 0.0, 0, 0.0, false, false, nullptr, 0}, // placeholder\n";
  params << "};\n";

  // UI size: @gfx size if given, else a size that fits the generic knob grid
  int uiW, uiH;
  if (hasGfx)
  {
    uiW = dim[0] ? static_cast<int>(dim[0]) : 640;
    uiH = dim[1] ? static_cast<int>(dim[1]) : 400;
  }
  else
  {
    const int cols = numVisible < kKnobsPerRow ? (numVisible ? numVisible : 1) : kKnobsPerRow;
    const int rows = (numVisible + kKnobsPerRow - 1) / kKnobsPerRow;
    uiW = std::max(360, cols * kCellW + 2 * kMargin);
    uiH = kHeaderH + std::max(1, rows) * kCellH + kMargin;
  }

  std::ostringstream meta;
  meta << "// Generated by jsfx_meta from " << jsfxPath << " - do not edit.\n#pragma once\n"
       << "#define JSFX_DESC " << CString(ysfx_get_name(fx)) << "\n"
       << "#define JSFX_NUM_INPUTS " << nIn << "\n"
       << "#define JSFX_NUM_OUTPUTS " << nOut << "\n"
       << "#define JSFX_CHANNEL_IO \"" << nIn << "-" << nOut << "\"\n"
       << "#define JSFX_HAS_GFX " << (hasGfx ? 1 : 0) << "\n"
       << "#define JSFX_GFX_WIDTH " << dim[0] << "\n"
       << "#define JSFX_GFX_HEIGHT " << dim[1] << "\n"
       << "#define JSFX_UI_WIDTH " << uiW << "\n"
       << "#define JSFX_UI_HEIGHT " << uiH << "\n"
       << "#define JSFX_NUM_PARAMS " << entries.size() << "\n";

  ysfx_free(fx);

  if (!WriteIfChanged(outDir + "/jsfx_meta.h", meta.str()) ||
      !WriteIfChanged(outDir + "/jsfx_params.inc", params.str()))
  {
    std::fprintf(stderr, "jsfx_meta: cannot write into %s\n", outDir.c_str());
    return 1;
  }
  std::printf("jsfx_meta: %s -> %zu parameter(s), %u in / %u out, %s\n", jsfxPath.c_str(),
              entries.size(), nIn, nOut, hasGfx ? "@gfx UI" : "generic UI");
  return 0;
}
